version: "2"

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - dupword
    - durationcheck
    - errchkjson
    - embeddedstructfieldcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocritic
    - gomoddirectives
    - goprintffuncname
    - iface
    - intrange
    - iotamixing
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - recvcheck
    - revive
    - sloglint
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
